service: cadastro-usuarios

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-2

functions:
  listarUsuarios:
    handler: handler.listarUsuarios
    events:
      - http:
          path: usuarios
          method: get