service: cadastro-usuarios

plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-2

functions:
  listarUsuarios:
    handler: handler.listarUsuarios
    events:
      - http:
          path: usuarios
          method: get
  obterUsuario:
    handler: handler.obterUsuario
    events:
      - http:
          path: usuarios/{usuarioId}
          method: get

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
      TableName: USUARIOS
      AttributeDefinitions:
        - AttributeName: usuario_id
          AttributeType: S
      KeySchema:
        - AttributeName: usuario_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1